//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDCrm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanicilar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kullanicilar()
        {
            this.KullaniciYetkilers = new HashSet<KullaniciYetkiler>();
        }
    
        public int ID { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public string SirketTelefonu { get; set; }
        public string Email { get; set; }
        public string Parola { get; set; }
        public Nullable<bool> Aktif { get; set; }
        public string Adres { get; set; }
        public string TC { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public string KisiselTelefon { get; set; }
        public string SirketTelefonKisaKod { get; set; }
        public string Zimmet { get; set; }
        public string Grubu { get; set; }
        public string Bilgilendirme { get; set; }
        public string Atama { get; set; }
        public string ModulYetkisi { get; set; }
        public string KisiselMail { get; set; }
        public string KayitYapanKullanici { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public string DuzenlemeYapanKullanici { get; set; }
        public Nullable<System.DateTime> DuzenlemeTarihi { get; set; }
        public Nullable<bool> Silindi { get; set; }
        public Nullable<System.DateTime> SilinenTarih { get; set; }
        public string SilenKullanici { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KullaniciYetkiler> KullaniciYetkilers { get; set; }
    }
}
