//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDCrm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KullaniciYetkiler
    {
        public int ID { get; set; }
        public Nullable<int> KullaniciID { get; set; }
        public string Modul { get; set; }
        public Nullable<bool> Gor { get; set; }
        public Nullable<bool> Duzenle { get; set; }
        public Nullable<bool> Sil { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
